name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: montudor/action-zip@v1
      with:
        args: zip -r file.zip ./

    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: file
        path: file.zip


